name: build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno: ['v1.x']
    name: Deno v${{ matrix.deno }}
    steps:
      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno }}
      - run: sudo apt-get install wkhtmltopdf
      - run: deno fmt --check
      - run: deno lint --unstable
      - run: deno test --allow-run --allow-write
